In [2]:
# Imports 

import pandas as pd
import numpy as np 
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

In [3]:
import pandas as pd

scaled = pd.read_csv('https://raw.githubusercontent.com/trackteam-spotify/data-science/master/data/final_scaled_dataset.csv')

scaled.head()

index        artist_name  ...  loudness     tempo
0      1   Nicholas Britell  ... -2.108236 -1.200244
1      2               Seeb  ...  1.254850  0.614084
2      3           Lagwagon  ...  0.643049 -0.479831
3      4      Super Whatevr  ... -1.292787  0.206582
4      5  The Front Bottoms  ...  0.942632  1.048378

[5 rows x 11 columns]

In [4]:
scaled.shape

(5000, 11)

## Modeling K-Nearest Neighbors

In [ ]:
# Variables to cluster

cluster = ['popularity', 'danceability', 'energy', 'instrumentalness', 'liveness', 'loudness', 'tempo']

distortion = list()
for k in range(1, 31): #started with range [1, 51] and narrowed down to this range 
    kmeans = KMeans(n_clusters = k)
    kmeans.fit(scaled.loc[:, cluster])
    distortion.append(kmeans.inertia_) # append distortion value to list

In [6]:
knn = NearestNeighbors(n_neighbors=15)
features = ['popularity', 'danceability', 'energy', 'instrumentalness', 'liveness', 'loudness', 'tempo']
X = scaled[features].values

knn.fit(X)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                 radius=1.0)

In [7]:
# test on 1 song
test_song = X[20]

distance, neighbors = knn.kneighbors(np.array([test_song]))
distance, neighbors

(array([[0.        , 0.63472403, 0.68087431, 0.68190637, 0.78568082,
         0.78977841, 0.79588194, 0.80620697, 0.8157036 , 0.81841708,
         0.82283869, 0.84523641, 0.84715768, 0.93537395, 0.93875525]]),
 array([[  20, 3806,  301, 2356, 3462, 1585, 1731, 1940, 2330,  695, 2353,
         1959,  849, 4776, 3544]]))

In [8]:
scaled.iloc[20]

index                                           21
artist_name                               Dua Lipa
track_name          New Rules - Initial Talk Remix
track_id                    2ygfHXyt3gvyhvKrNJU61n
popularity                                0.750656
danceability                             -0.341411
energy                                     1.59248
instrumentalness                         -0.398629
liveness                                 -0.235938
loudness                                   1.15463
tempo                                    -0.108978
Name: 20, dtype: object

## New playlist based off user input

In [9]:
song_list = []
for item in neighbors[0][1:]: # this way excludes itself
    row = scaled.iloc[item]
    song_list.append((row.track_name, row.artist_name))
    
names = ['song', 'artist']

new_playlist = pd.DataFrame(song_list, columns=names)
print(new_playlist.shape)
new_playlist

(14, 2)


song                    artist
0              On the Line - Featuring Jonas Brothers            Jonas Brothers
1                                       Uncomfortable                 Halestorm
2                                               Jaded                 Aerosmith
3                                   Apocalypse Dreams               Tame Impala
4                                          Adrenalize            In This Moment
5                                      The Other Side              Jason Derulo
6                              Honky Tonk Badonkadonk              Trace Adkins
7                                      My Dilemma 2.0  Selena Gomez & The Scene
8                                    Rhinestone World              Dallas Smith
9                              Desire - Gryffin Remix             Years & Years
10                                            Stupify                 Disturbed
11                                      Shooting Star                  Owl City
12                                            Howling                      FLOW
13  Ocean to Ocean (From Aquaman: Original Motion ...                   Pitbull

## Pickle the Model


In [9]:
import joblib
joblib.dump(knn, 'model.pkl')

['model.pkl']

In [10]:
model = joblib.load('model.pkl')

In [11]:
model.kneighbors(X[11].reshape(1,-1))[1][0][1:]

array([  59, 3770,  360,  516,  102, 4828, 2162, 2257, 1526, 2219, 1453,
       4906, 4911, 1166])

## Sentiment Analysis (Pre-trained Neural Network)

In [10]:
!pip install vaderSentiment

     |████████████████████████████████| 133kB 9.8MB/s 


In [11]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Using a pretrained neural network to encode title to numbers
# Adding numbers to column as sentiments
sentiments =[] 
analyzer = SentimentIntensityAnalyzer()
for sentence in scaled['track_name']:
  vs = analyzer.polarity_scores(sentence)
  sentiments.append(vs['compound'])
scaled['sentiments'] = sentiments

In [12]:
scaled.sort_values(by=['sentiments'],ascending=False).head(5)

index         artist_name  ...     tempo sentiments
4275   4276               LANCO  ... -1.433452     0.8555
259     260         Jeff Mangum  ... -0.946180     0.8555
4824   4825         Céline Dion  ... -0.690137     0.8555
598     599       Andy Williams  ... -1.523315     0.8442
4767   4768  Natalia Lafourcade  ... -0.495322     0.8402

[5 rows x 12 columns]

In [13]:
scaled.sort_values(by=['sentiments'],ascending=False).tail(5)

index      artist_name  ...     tempo sentiments
1444   1445         Kid Cudi  ... -0.462764    -0.7906
3027   3028       Rich Brian  ...  0.845482    -0.7964
4460   4461    Natti Natasha  ...  0.171945    -0.8225
576     577  Little Big Town  ...  1.414603    -0.8225
3761   3762     Scott Helman  ... -0.494618    -0.8519

[5 rows x 12 columns]

## Visualization 1

In [14]:
import plotly.graph_objects as go

categories = ['popularity', 'danceability', 'energy', 'instrumentalness', 'tempo']

fig = go.Figure()


fig.add_trace(go.Scatterpolar(
      r=[0.75, -0.34, 1.59, -0.39, -0.10],
      theta=categories,
      fill='toself',
      name='New Rules - Dua Lipa'
))
fig.add_trace(go.Scatterpolar(
      r=[0.63, -0.57, 1.38, 0.02, 0.27],
      theta=categories,
      fill='toself',
      name='Apocalypse Dreams - Tame Impala'
))
fig.add_trace(go.Scatterpolar(
      r=[0.52, -0.11, 1.26, -0.39, 0.17],
      theta=categories,
      fill='toself',
      name='On The Line - Jonas Brothers'
))

fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[-2, 2]
    )),
  showlegend=False
)

fig.show()

## Visualization 2 

In [15]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Build-Week-Spotify-Song-Suggester-5/Data-Science/master/app/most_popular_spotify_songs.csv')

df.head()

genre     artist_name  ... time_signature valence
0   R&B   Mary J. Blige  ...            4/4  0.6930
1   R&B         Rihanna  ...            3/4  0.3230
2   R&B       Yung Bleu  ...            4/4  0.0862
3   R&B        Surfaces  ...            4/4  0.7680
4   R&B  Olivia O'Brien  ...            4/4  0.4660

[5 rows x 18 columns]

In [16]:
# Compare/contrast genres
groupby_genre = df.groupby(['genre'])
genre_musical_attributes = groupby_genre.mean()

genre_musical_attributes.sort_values(by=['popularity'],ascending=False)

popularity  acousticness  ...       tempo   valence
genre                                       ...                      
Pop                67.168938      0.253703  ...  123.306378  0.505836
Rap                59.655840      0.223981  ...  121.026423  0.442050
Rock               59.165608      0.208770  ...  122.918544  0.513846
Hip-Hop            58.622716      0.173847  ...  122.017802  0.461974
Dance              58.329712      0.155698  ...  120.677401  0.517677
Indie              53.748256      0.310207  ...  120.680002  0.452243
Children’s Music   53.473438      0.150533  ...  122.549317  0.440069
Alternative        51.028906      0.161020  ...  122.325118  0.449224
Folk               50.922760      0.482245  ...  118.489007  0.427171
Reggaeton          50.515120      0.224959  ...  122.575213  0.639940
R&B                49.580658      0.302320  ...  116.314936  0.448499
Movie              49.189504      0.728951  ...  108.887184  0.371989
Country            48.613067      0.273603  ...  123.449817  0.542532
Reggae             48.539468      0.187375  ...  118.544447  0.684584
Soul               47.598422      0.345051  ...  115.412118  0.489340
Electronic         47.532116      0.119440  ...  125.213006  0.391148
Jazz               47.413621      0.540679  ...  110.359795  0.495971
Blues              47.352325      0.340669  ...  120.335902  0.576963
Ska                47.257855      0.091720  ...  131.663056  0.664063
World              46.651761      0.367432  ...  122.495178  0.261533
Classical          46.649644      0.793293  ...  105.468918  0.209354
Soundtrack         46.608273      0.695152  ...  103.976154  0.113138
Anime              46.419014      0.147398  ...  131.379421  0.490420
Opera              45.974684      0.930848  ...  101.163241  0.201656
Comedy             44.353333      0.767230  ...  101.280577  0.387063
Children's Music   44.000000      0.474848  ...  113.821667  0.730762
A Capella          44.000000      0.780000  ...   82.471000  0.712000

[27 rows x 11 columns]

In [17]:
# Popularity By Genre

import plotly.graph_objects as go
import plotly.express as px

fig = go.Figure()
fig.add_trace(go.Bar(
    y= ['Pop', 'Rap', 'Rock', 'Hip-Hop', 'Dance', 'Indie', 'Childrens Music', 'Alternative', 'Folk', 'Raggaeton', 'R&B', 'Movie',
        'Country', 'Raggae', 'Soul', 'Electronic', 'Jazz'],
    
    x= [67, 59, 59, 58, 58, 53, 53, 51, 50, 50, 49, 49, 48, 48, 47, 47, 47],
    name='Genre',
    orientation='h',
    marker=dict(
        color='rgba(2, 181, 8, 0.6)',
        line=dict(color='rgba(105, 105, 105, 1.0)', width=1)      
    ) 
))
fig.update_layout(barmode='stack')
fig.update_layout(
  title_text="Popularity By Genre"),

# Source
annotations = []
annotations.append(dict(xref='paper', yref='paper',
                        x=0, y=-0.15,
                        text='Source: https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks',
                        font=dict(family='Arial', size=13, color='rgb(150,150,150)'),
                        showarrow=False))

fig.update_layout(annotations=annotations)
fig.show()

## Hard Code Input Dictionary

In [ ]:
def model_maker():

  # Variables to cluster
  cluster = ['popularity', 'danceability', 'energy', 'instrumentalness', 'liveness', 'loudness', 'tempo']

  distortion = list()
  for k in range(1, 31): #started with range [1, 51] and narrowed down to this range 
      kmeans = KMeans(n_clusters = k)
      kmeans.fit(scaled.loc[:, cluster])
      distortion.append(kmeans.inertia_) # append distortion value to list
  
  # Modeling K-Nearest Neighbors
  knn = NearestNeighbors(n_neighbors=15)
  features = ['popularity', 'danceability', 'energy', 'instrumentalness', 'liveness', 'loudness', 'tempo']
  X = scaled[features].values

  knn.fit(X)



# test on 1 song
test_song = X[user_input]

distance, neighbors = knn.kneighbors(np.array([test_song]))

knn = model_maker()

def predict(user_input):

  # test on 1 song
  test_song = X[user_input]

  distance, neighbors = knn.kneighbors(np.array([test_song]))

  song_list = []
  for item in neighbors[0][1:]: # this way excludes itself
      row = scaled.iloc[item]
      song_list.append((row.track_name, row.artist_name))
    
  names = ['song', 'artist']

  new_playlist = pd.DataFrame(song_list, columns=names)

In [ ]:
predict(user_input)